### ISSUE TITLE
On Google TTS

### ISSUE THREAD

**Issue by dipkamal** [desbma/GoogleSpeech#11]
Hello, your program is pretty amazing btw. Eases to use the google tts. Thank you. 
I just wanted to know how long we could use the google tts for free this way? Wont our ip get blocked accessing the service too often or what's the rate to be safe from blocking? I also heard this service is now outdated and it could be closed anytime soon. Any information on it would help me a lot. 
Thanks.

**Comment by desbma** [comment]
Hi,

Yes your IP can be blocked if you access the Google servers too much. I don't know what is the exact rate above which Google blocks IPs. You'd have to experiment to find the threshold. However, the local cache should help avoid getting blocked if you often use the same text.

It is using an unofficial API, so yes it also may be closed at any time. However Google's own services, like Google translate, use this API, so it unlikely to completely disappear.

Hope that answers you questions

**Comment by dipkamal** [comment]
Thank you for the info.
