### ISSUE TITLE
how to add PAUSE feature?

### ISSUE THREAD

**Issue by crysman** [desbma/GoogleSpeech#13]
hello, anyone familiar with the source code... how to add PAUSE feature? (e.g. by pressing "Pause/Break" key)? Thanks

**Comment by desbma** [comment]
Hi,

Currently [SoX](https://sourceforge.net/projects/sox/) is used to play audio, and there is no pause feature.

If you are on a Unix system you could try to send signals to the player process, see [here](https://sourceforge.net/p/sox/mailman/message/26419988/) for example.
