### ISSUE TITLE
How can I use this amazing script read aloud selected text with a keyboard shortcut?

### ISSUE THREAD

**Issue by anonyxuser1** [desbma/GoogleSpeech#15]
This is such a nice script! Such a beautiful voice too! Wow! Thank you!

I have one huge thing that I am trying to accomplish... how can I use this script to read alloud my selected text anywhere on my system with a simple keyboard shortcut? I was thinking xclip but I wouldnt know how to do that. Could you guide me or help me out here? I would be so thankfull! Thanks so much for your time!

Best,
Anony

**Comment by desbma** [comment]
Assuming you are on Linux with Bash and xclip installed, the following command should read the currently selected text: 
`google_speech -l en "$(xclip -out -selection primary)"` 

You'd have to put that in a script, and execute it with a keyboard shortcut in your desktop environment.
