### ISSUE TITLE
sox FAIL formats: no handler for given file type `mp3'

### ISSUE THREAD

**Issue by pannous** [desbma/GoogleSpeech#20]
smarter error handling would be 
```
PLEASE install:
sudo apt-get install libsox-fmt-mp3
```

**Comment by desbma** [comment]
That is not what error handling is.

What about users not on Ubuntu, not on Linux, without sudo/root access, etc.?

By the way from the Readme:
> On Ubuntu and other Debian derivatives: sudo apt-get install sox libsox-fmt-mp3.
